### ISSUE TITLE
usb.core.util 通信会不会快些？

### ISSUE THREAD

**Issue by wutaijieing** [rotriw/UnlockHuaweiBootloader#1]
usb.util通信会不会快些？
send_bulk：oem unock xxx
而且不会有平台限制

**Comment by hg56th56gd6g** [comment]
感谢反馈,目前手边环境受限,没有设备难以调试usb
由于usb的复杂性,以及确保fastboot的兼容性,如果还有更新,应该还是以AdbWinApi为主的
