### ISSUE TITLE
请教，工具如何使用？

### ISSUE THREAD

**Issue by javon4016** [rotriw/UnlockHuaweiBootloader#2]
您好，感谢您的分享，我的手机华为hi nova9 hera-bd00想要root，网上说要先解锁bl。您这个工具要如何使用进行解锁bl，有没有详细一点的步骤教程？期待回复，感谢！

**Comment by sunrise232** [comment]
把工具和platform-tools文件夹丢到同一个目录

**Comment by hg56th56gd6g** [comment]
此工具只是重复命令 fastboot oem unlock <解锁码>
可以参考此文章: https://sspai.com/post/23628
视手机型号不同,后续步骤可能不一样,且不保证绝对可用
