### ISSUE TITLE
可行吗？

### ISSUE THREAD

**Issue by Conichiwa-Saodeisiga** [rotriw/UnlockHuaweiBootloader#7]
如果以每秒输入 10 个序列号的速度，完成输入所有 47,672,401,706,823,533,450,263,330,816 个序列号需要大约 4.77 × 10²⁷ 秒。
换算成更直观的单位，这大约是 1.51 × 10²⁰ 年，远远超过人类历史的时间尺度！这显示了16位序列号的数量之庞大。

**Comment by hg56th56gd6g** [comment]
旧作翻新,解锁方式是很老的了,不保证新设备可用,不保证可行,设备若出现问题请自行负责
